# Generated by Django 3.2.9 on 2021-11-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('animal_label', models.IntegerField()),
                ('animal_name', models.CharField(max_length=50)),
                ('animal_title', models.CharField(max_length=300)),
                ('animal_disc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
